# 1

In [6]:
import pandas as pd

data = pd.DataFrame({
    "Date": ["2023-01-19", "2023-01-16", "2023-01-10", "2023-01-18", "2023-01-14", 
             "2023-01-06", "2023-01-04", "2023-01-09", "2023-01-20", "2023-01-11", 
             "2023-01-13", "2023-01-08", "2023-01-15", "2023-01-05", "2023-01-01", 
             "2023-01-03", "2023-01-02", "2023-01-07", "2023-01-12", "2023-01-17"],
    "Account_Type": ["Fixed Deposit", "Current", "Current", "Savings", "Recurring Deposit", 
                     "Current", "Recurring Deposit", "Current", "Recurring Deposit", "Fixed Deposit", 
                     "Recurring Deposit", "Fixed Deposit", "Fixed Deposit", "Recurring Deposit", "Fixed Deposit", 
                     "Savings", "Fixed Deposit", "Current", "Recurring Deposit", "Savings"],
    "Branch": ["Central", "Uptown", "Uptown", "Uptown", "Suburban", 
               "Suburban", "Central", "Central", "Downtown", "Downtown", 
               "Central", "Suburban", "Uptown", "Central", "Downtown", 
               "Suburban", "Central", "Central", "Suburban", "Central"],
    "Transaction_Type": ["Loan Payment", "Withdrawal", "Loan Payment", "Loan Payment", "Loan Payment", 
                         "Service Charge", "Service Charge", "Loan Payment", "Service Charge", "Deposit", 
                         "Deposit", "Service Charge", "Service Charge", "Loan Payment", "Withdrawal", 
                         "Service Charge", "Deposit", "Loan Payment", "Service Charge", "Deposit"],
    "Transaction_Amount": [985.51, 641.43, 3363.85, 1914.6, 2788.57, 
                           4584.05, 1621.82, 2346.72, 3899.98, 1529.59, 
                           846.41, 1803.88, 1225.5, 4683.64, 4136.54, 
                           3350.32, 4421.57, 4116.52, 1339.57, 4516.52],
    "Account_Balance": [6839.59, 8908.39, 12428.67, 5776.63, 4779.04, 
                        7635.47, 6465.79, 10708.85, 12646.56, 2592.16, 
                        6443.14, 6560.58, 4224.47, 6762.43, 8175.08, 
                        12836.51, 8330.4, 9785.64, 8666.74, 8789.19]
})

print("First 5 rows of the dataset:")
print(data.head())

print("\nBasic statistics for numerical columns:")
print(data[["Transaction_Amount", "Account_Balance"]].describe())

print("\nMissing values in the dataset:")
print(data.isnull().sum())

First 5 rows of the dataset:
         Date       Account_Type    Branch Transaction_Type  \
0  2023-01-19      Fixed Deposit   Central     Loan Payment
1  2023-01-16            Current    Uptown       Withdrawal
2  2023-01-10            Current    Uptown     Loan Payment
3  2023-01-18            Savings    Uptown     Loan Payment
4  2023-01-14  Recurring Deposit  Suburban     Loan Payment

   Transaction_Amount  Account_Balance
0              985.51          6839.59
1              641.43          8908.39
2             3363.85         12428.67
3             1914.60          5776.63
4             2788.57          4779.04

Basic statistics for numerical columns:
       Transaction_Amount  Account_Balance
count           20.000000        20.000000
mean          2705.829500      7967.766500
std           1429.829787      2770.248821
min            641.430000      2592.160000
25%           1482.085000      6460.127500
50%           2567.645000      7905.275000
75%           4121.525000      9127.702500
max           4683.640000     12836.510000

Missing values in the dataset:
Date                  0
Account_Type          0
Branch                0
Transaction_Type      0
Transaction_Amount    0
Account_Balance       0
dtype: int64

# 2

In [10]:
import pandas as pd

data = pd.DataFrame({
    "Date": ["2023-01-19", "2023-01-16", "2023-01-10", "2023-01-18", "2023-01-14", 
             "2023-01-06", "2023-01-04", "2023-01-09", "2023-01-20", "2023-01-11", 
             "2023-01-13", "2023-01-08", "2023-01-15", "2023-01-05", "2023-01-01", 
             "2023-01-03", "2023-01-02", "2023-01-07", "2023-01-12", "2023-01-17"],
    "Account_Type": ["Fixed Deposit", "Current", "Current", "Savings", "Recurring Deposit", 
                     "Current", "Recurring Deposit", "Current", "Recurring Deposit", "Fixed Deposit", 
                     "Recurring Deposit", "Fixed Deposit", "Fixed Deposit", "Recurring Deposit", "Fixed Deposit", 
                     "Savings", "Fixed Deposit", "Current", "Recurring Deposit", "Savings"],
    "Branch": ["Central", "Uptown", "Uptown", "Uptown", "Suburban", 
               "Suburban", "Central", "Central", "Downtown", "Downtown", 
               "Central", "Suburban", "Uptown", "Central", "Downtown", 
               "Suburban", "Central", "Central", "Suburban", "Central"],
    "Transaction_Type": ["Loan Payment", "Withdrawal", "Loan Payment", "Loan Payment", "Loan Payment", 
                         "Service Charge", "Service Charge", "Loan Payment", "Service Charge", "Deposit", 
                         "Deposit", "Service Charge", "Service Charge", "Loan Payment", "Withdrawal", 
                         "Service Charge", "Deposit", "Loan Payment", "Service Charge", "Deposit"],
    "Transaction_Amount": [985.51, 641.43, 3363.85, 1914.6, 2788.57, 
                           4584.05, 1621.82, 2346.72, 3899.98, 1529.59, 
                           846.41, 1803.88, 1225.5, 4683.64, 4136.54, 
                           3350.32, 4421.57, 4116.52, 1339.57, 4516.52],
    "Account_Balance": [6839.59, 8908.39, 12428.67, 5776.63, 4779.04, 
                        7635.47, 6465.79, 10708.85, 12646.56, 2592.16, 
                        6443.14, 6560.58, 4224.47, 6762.43, 8175.08, 
                        12836.51, 8330.4, 9785.64, 8666.74, 8789.19]
})

account_grouped = data.groupby("Account_Type").agg({
    "Transaction_Amount": "sum",
    "Account_Balance": "mean"
}).rename(columns={
    "Transaction_Amount": "Total_Transaction_Amount",
    "Account_Balance": "Average_Account_Balance"
})

print("Aggregated data by Account_Type:")
print(account_grouped)

branch_grouped = data.groupby("Branch").agg({
    "Transaction_Amount": ["count", "mean"]
}).rename(columns={
    "count": "Total_Transactions",
    "mean": "Average_Transaction_Amount"
})

branch_grouped.columns = branch_grouped.columns.map("_".join)
branch_grouped = branch_grouped.rename(columns={
    "Transaction_Amount_count": "Total_Transactions",
    "Transaction_Amount_mean": "Average_Transaction_Amount"
})

print("\nAggregated data by Branch:")
print(branch_grouped)

Aggregated data by Account_Type:
                   Total_Transaction_Amount  Average_Account_Balance
Account_Type
Current                            15052.57              9893.404000
Fixed Deposit                      14102.59              6120.380000
Recurring Deposit                  15179.99              7627.283333
Savings                             9781.44              9134.110000

Aggregated data by Branch:
          Transaction_Amount_Total_Transactions  \
Branch
Central                                       8
Downtown                                      3
Suburban                                      5
Uptown                                        4

          Transaction_Amount_Average_Transaction_Amount
Branch
Central                                     2942.338750
Downtown                                    3188.703333
Suburban                                    2773.278000
Uptown                                      1786.345000